### ISSUE TITLE
Register window, nezavira se

### ISSUE THREAD

**Issue by DDvory** [stechy1/drd#128]
Registracni okno se nezavira po uspesnem ukonceni registrace. (ps je to stejne jako u logginu a stejne to nefunguje)

**Comment by stechy1** [comment]
Díky za nahlášení chyby. Po krátkém zkoumání kódu jsem zjistil, že přeci jenom menší rozdíl ve funkcich handleLogin a handleRegister. V registraci se omylem nachází asynchronní zpracování výsledků po registraci. Když se podíváš do kódu pozorně, najdeš u loginu volání _thenAccept_  a v registraci se místo toho volá _thenAcceptAsync_ což má za následek nezavreni okna.

**Comment by stechy1** [comment]
Hotovo
