### ISSUE TITLE
Instalace/Spuštění aplikace

### ISSUE THREAD

**Issue by martinstepanek** [stechy1/drd#94]
Ahoj,
mohl bys jednou za čas verzi programu nějakým způsobem zabalit/připravit? Tím myslím, aby ti méně schopní jako já, pro které je postup spuštění programu moc složitý i s přiloženým postupem si mohli aplikaci spustit bez sestavování projektu. :-)

**Comment by stechy1** [comment]
Aplikace se tu jistě objeví, jen zatím dodržuji pravidla soutěže, kde je psáno, že aplikaci nemůžu vydat před skončením soutěže. Samozřejmě ji sem pak budu dávat.

**Comment by stechy1** [comment]
V záložce [release](https://github.com/stechy1/drd/releases) jsem už nahrál první veřejné sestavení aplikace
